language: en-US
checkUpdates: true

tablist-faker:
  enabled: false
  #You can also use /fpmb tablist add/remove to add/remove fake players' names from the tablist.
  #if you don't want to use the default player list, you can leave it empty.
  defaultPlayerList: []
  useFakePlayerPrefix: false

fakePlayerPrefix: "&a[Fake Player] &f"

#Use for contract backend servers
backend:
  #Turn on so that fake players can join to the destination backend server.
  enabled: true